language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t mizkuzy/docker-aws-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mizkuzy/docker-aws-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-aws-react"
  env: "DockerAwsReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-530368369186"
  bucket_path: "docker-aws-react"
  on:
    branch: master
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
